<?php
/**
 *	Kalium WordPress Theme
 *
 *	Laborator.co
 *	www.laborator.co
 */

# Var to tell simple thumbnail if there is actually post format content to be parsed
$blog_post_format_parsed = false;

if( ! $blog_post_formats)
{
	return;
}
?>

<?php
# Post Format - Image
if($post_format == 'image' && $post_image['content']):

	$blog_post_format_parsed = true;
	
	$guid = $post_image['content'];
	$thumb = $guid;

	if($post_thumbnail_id)
	{
		$guid = $thumbnail_big->guid;
		$thumb = $thumbnail_url;
	}
?>
<a href="<?php echo esc_url($permalink); ?>">
	<img <?php echo $blog_post_list_lazy_load ? 'data-' : ''; ?>src="<?php echo esc_url($thumb); ?>" alt="post-img-<?php echo esc_attr($post_id); ?>" />
	
	<?php
	if( ! is_singular())
	{
		include locate_template('tpls/post-hover.php');
	}
	?>
</a>
<?php

endif;
# End of: Post Format - Image
?>

<?php 
# Post Format - Video
if($post_format == 'video' && $post_video['content']): 
?>

	<?php if(isset($post_video['data']['type']) && in_array($post_video['data']['type'], array('native', 'youtube', 'vimeo'))):
			
			$blog_post_format_parsed = true;
			
			$video_resolution = get_field('video_resolution');
			
			if( ! preg_match("/([0-9]+x[0-9]+)|([0-9]+:[0-9]+)/", $video_resolution))
			{
				$video_resolution = '16:9';
			}
			
			$video_resolution = explode('x', str_replace(':', 'x', $video_resolution));
			$video_resolution_padding = $video_resolution[1] / $video_resolution[0] * 100;
			
			generate_custom_style(".post-{$post_id} .thumb .music-video-holder", "padding-top: {$video_resolution_padding}%");
			
    		wp_enqueue_script('video-js');
    		wp_enqueue_style('video-js');

    		if($post_video['data']['type'] == 'youtube')
    		{
	    		wp_enqueue_script('video-js-youtube');
	    	}

    		if($post_video['data']['type'] == 'vimeo')
    		{
	    		wp_enqueue_script('video-js-vimeo');
	    	}
	?>
	<div class="music-video-holder<?php echo " video-type-" . $post_video['data']['type']; ?>">
    	<?php echo $post_video['content']; # generated by [video] shortcode ?>
	</div>
	<?php endif; ?>

<?php 
endif;
# End of: Post Format - Video
?>

<?php 
# Post Format - Audio
if($post_format == 'audio' && $post_audio['content']): 
?>

	<?php
	$blog_post_format_parsed = true;
		
	wp_enqueue_script('video-js');
	wp_enqueue_style('video-js');
	
	if($post_thumbnail_id)
	{
		$img_attachment = wp_get_attachment_image_src($post_thumbnail_id, $thumb_size);
		
		if($img_attachment)
		{
			$audio_element_aspect_ratio = laborator_generate_as_element(array($img_attachment[1], $img_attachment[2]));
		}
		
		
	}

	?>
	<div class="music-video-holder video-type-audio <?php echo isset($audio_element_aspect_ratio) ? $audio_element_aspect_ratio : ''; ?>">
		<?php echo $post_audio['content']; # generated by [audio] shortcode ?>
	</div>

<?php 
endif;
# End of: Post Format - Audio
?>

<?php
# Post Format - Link
if($post_format == 'link' && $post_link['content']):
	
	$blog_post_format_parsed = true;
	
	$permalink = $post_link['content'];
	
	include locate_template('tpls/post-thumbnail-simple.php');
	
	$permalink = get_permalink();
	
endif;
# End of: Post Format - Link
?>

<?php
# Post Format - Quote
if($post_format == 'quote' && $post_quote['content']):
	
	$blog_post_format_parsed = true;
?>
<div class="quote-holder">
	<blockquote><?php
		echo $post_quote['content']; # no escape needed, this is get_the_content()

		if(isset($post_quote['data']['cite']))
		{
			echo "<cite>" . $post_quote['data']['cite'] . "</cite>";
		}
	?></blockquote>
</div>
<?php 
endif; 
# End of: Post Format - Quote
?>

<?php
# Post Format - Gallery
if($post_format == 'gallery' && ($post_thumbnail_id || count($slider_images))):
	
	$blog_post_format_parsed = true;
	
	?>
	<div class="post-gallery">
	<?php
		$i = 0;
		
		wp_enqueue_script('slick');
		wp_enqueue_style('slick');
		
		if($post_thumbnail_id)
		{
			$post_attach = get_post($post_thumbnail_id, $thumb_size);
			
			$link = is_single() ? $post_attach->guid : $permalink;
			$alt_text = $post_attach->_wp_attachment_image_alt;
			$is_video = $alt_text && preg_match("/(youtube\.com|vimeo\.com)/i", $alt_text);
			
			if($is_video)
			{
				$link = $alt_text;
			}
			
			?>
			<a href="<?php echo esc_url($link); ?>" data-lightbox-gallery="post-gallery">
				<?php laborator_show_image_placeholder($post_thumbnail_id, $thumb_size, '', $blog_post_list_lazy_load); ?>
			</a>
			<?php
			$i++;
		}
		
		foreach($slider_images as $image):
		
			$link = is_single() ? $image['url'] : $permalink;
			
			$is_video = isset($image['caption']) && preg_match("/(youtube\.com|vimeo\.com)/i", $image['caption']);
			
			if($is_video)
			{
				$link = $image['caption'];
			}
			
			?>
			<a href="<?php echo esc_url($link); ?>" class="<?php when_match($i > 0, 'hidden'); ?>"<?php if(is_single()): ?> data-lightbox-gallery="post-gallery"<?php endif; ?>>
				<?php echo laborator_show_image_placeholder($image['id'], $thumb_size, '', $blog_post_list_lazy_load); ?>
			</a>
			<?php
			
			$i++;
		endforeach;
	?>
	</div>
	<?php
	
endif;
# End of: Post Format - Link
?>